# rxyhn's aesthetic alacritty
# configuration for alacritty, the GPU enhanced terminal emulator.
import:
  - .config/alacritty/themes/night.yml

env:
  TERM: xterm-256color

window:
  dynamic_padding: true

  padding:
    x: 25
    y: 25

font:
  normal:
    family: Iosevka Nerd Font Mono
    style: Regular

  bold:
    family: Iosevka Nerd Font Mono
    style: Bold

  italic:
    family: Iosevka Nerd Font Mono
    style: Italic

  bold_italic:
    family: Iosevka Nerd Font Mono
    style: Bold Italic

  size: 10

  offset:
    x: 0
    y: 0

cursor:
  style: Underline

live_config_reload: true
